version: '3.8'

services:

  websocket:
    image: openv2x/lidar:latest
    container_name: websocket
    network_mode: host
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - redis_password=${OPENV2X_REDIS_ROOT}
      - host=127.0.0.1
    depends_on:
      - redis

  worker:
    image: openv2x/lidar:latest
    container_name: celery_worker
    command: celery worker --app=worker.celery -l info
    network_mode: host
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://:${OPENV2X_REDIS_ROOT}@127.0.0.1:6378/0
      - host=127.0.0.1
      - redis_password=${OPENV2X_REDIS_ROOT}
    depends_on:
      - websocket
      - redis

  udp_server:
    image: openv2x/lidar:latest
    container_name: udp_server
    command: python3 udp_server.py
    network_mode: host
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://:${OPENV2X_REDIS_ROOT}@127.0.0.1:6378/0
      - host=127.0.0.1
      - redis_password=${OPENV2X_REDIS_ROOT}
    depends_on:
      - redis
      - worker

  udp_client:
    image: openv2x/lidar:latest
    container_name: udp_client
    command: python3 udp_client.py
    network_mode: host
    restart: always
    environment:
      - udp_host=127.0.0.1
      - host=127.0.0.1
      - redis_password=${OPENV2X_REDIS_ROOT}
    depends_on:
      - udp_server

  redis:
    image: redis:6.2.4-alpine
    container_name: lidar_redis
    restart: always
    command: redis-server --requirepass ${OPENV2X_REDIS_ROOT}
    ports:
      - 6378:6379

